Repository MSU-CS4360-WhiteHat/ecommerce-scam-detector, pull requests merged in 2023-02, with the labels that each got.

#18 Feature/9 web browser local storage
  background.js
Labels: Spike, feature

#22 Defect has been addressed
  background.js
Labels: bug

#38 make a simple string split that should suffice.
  background.js
Labels: bug

#49 Feature/34 UI design mockups
  manifest.json
  src/background/background.js
  src/popup/popup.css
  src/popup/popup.html
  src/popup/popup.js
Labels: feature
